name: quixotic
dependencies:
- alabaster=0.7.6=py34_0
- appnope=0.1.0=py34_0
- babel=2.1.1=py34_0
- backports_abc=0.4=py34_0
- bcolz=0.12.1=np110py34_0
- blaze=0.8.3=py34_0
- blaze-core=0.8.3=py34_0
- bokeh=0.10.0=py34_0
- cycler=0.9.0=py34_0
- cytoolz=0.7.4=py34_0
- datashape=0.4.7=np110py34_1
- decorator=4.0.4=py34_0
- docutils=0.12=py34_0
- flask=0.10.1=py34_1
- freetype=2.5.5=0
- h5py=2.5.0=np110py34_4
- hdf5=1.8.15.1=2
- ipykernel=4.1.1=py34_0
- ipython=4.0.0=py34_1
- ipython_genutils=0.1.0=py34_0
- ipywidgets=4.1.0=py34_0
- itsdangerous=0.24=py34_0
- jedi=0.9.0=py34_0
- jinja2=2.8=py34_0
- jsonschema=2.4.0=py34_0
- jupyter=1.0.0=py34_0
- jupyter_client=4.1.1=py34_0
- jupyter_console=4.0.3=py34_0
- jupyter_core=4.0.6=py34_0
- libpng=1.6.17=0
- llvmlite=0.8.0=py34_0
- markupsafe=0.23=py34_0
- matplotlib=1.5.0=np110py34_0
- mistune=0.7.1=py34_0
- multipledispatch=0.4.8=py34_0
- mysql-connector-python=2.0.3=py34_0
- nbconvert=4.0.0=py34_0
- nbformat=4.0.1=py34_0
- networkx=1.10=py34_0
- notebook=4.0.6=py34_0
- numba=0.22.1=np110py34_0
- numexpr=2.4.4=np110py34_0
- numpy=1.10.2=py34_0
- odo=0.3.4=py34_0
- openssl=1.0.2d=0
- pandas=0.17.1=np110py34_0
- path.py=8.1.2=py34_0
- pep8=1.6.2=py34_0
- pexpect=3.3=py34_0
- pickleshare=0.5=py34_0
- pip=7.1.2=py34_0
- psutil=3.3.0=py34_0
- ptyprocess=0.5=py34_0
- pyflakes=1.0.0=py34_0
- pygments=2.0.2=py34_0
- pymongo=3.0.3=py34_0
- pyparsing=2.0.3=py34_0
- pyqt=4.11.4=py34_1
- pytables=3.2.2=np110py34_0
- python=3.4.3=2
- python-dateutil=2.4.2=py34_0
- python.app=1.2=py34_4
- pytz=2015.7=py34_0
- pyyaml=3.11=py34_1
- pyzmq=14.7.0=py34_1
- qt=4.8.7=1
- qtconsole=4.1.0=py34_0
- readline=6.2=2
- requests=2.8.1=py34_0
- rope=0.9.4=py34_1
- setuptools=19.1.1=py34_0
- simplegeneric=0.8.1=py34_0
- sip=4.16.9=py34_0
- six=1.10.0=py34_0
- snowballstemmer=1.2.0=py34_0
- sphinx=1.3.1=py34_0
- sphinx_rtd_theme=0.1.7=py34_0
- spyder=2.3.7=py34_1
- sqlalchemy=1.0.10=py34_0
- sqlite=3.8.4.1=1
- terminado=0.5=py34_1
- tk=8.5.18=0
- toolz=0.7.4=py34_0
- tornado=4.3=py34_0
- traitlets=4.0.0=py34_0
- werkzeug=0.11.2=py34_0
- wheel=0.26.0=py34_1
- xz=5.0.5=0
- yaml=0.1.6=0
- zeromq=4.1.3=0
- zlib=1.2.8=0
- pip:
  - backports-abc==0.4
  - google-api-python-client==1.4.2
  - httplib2==0.9.2
  - ipython-genutils==0.1.0
  - jupyter-client==4.1.1
  - jupyter-console==4.0.3
  - jupyter-core==4.0.6
  - oauth2client==1.5.2
  - pyasn1==0.1.9
  - pyasn1-modules==0.0.8
  - pymysql==0.6.7
  - rope-py3k-0.9.4==1
  - rsa==3.2.3
  - simplejson==3.8.1
  - sphinx-rtd-theme==0.1.7
  - tables==3.2.2
  - uritemplate==0.6

